name: Run Unit Tests
on:
  pull_request:
    branches: [ "main" ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up libcunit
        run: sudo apt-get install -y gcc libcunit1-dev

      - name: Build unit tests
        run: gcc test.c -o test-calc -l cunit

      - name: Run unit tests
        run: ./test-calc

  e2e-tests:
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true  
          tags: |
            koval1621/calc:${{ github.sha }}
            koval1621/calc:latest

      - name: Run end-to-end tests
        run: |
          chmod +x e2e-tests.sh
          ./e2e-tests.sh "koval1621/calc:${{ github.sha }}"
